-- EHDP Sprint 2: PostgreSQL analytical star schema
-- Safe to rerun: this script does not drop existing schemas or tables.
-- Load dimensions before facts. Use source IDs from cleaned Synthea CSVs.
CREATE SCHEMA IF NOT EXISTS warehouse;

CREATE TABLE IF NOT EXISTS warehouse.dim_patient (
 patient_id VARCHAR(64) PRIMARY KEY, birthdate DATE, deathdate DATE,
 gender VARCHAR(20), race VARCHAR(100), ethnicity VARCHAR(100),
 marital_status VARCHAR(20), city VARCHAR(150), state VARCHAR(100), postal_code VARCHAR(20)
);
CREATE TABLE IF NOT EXISTS warehouse.dim_organization (
 organization_id VARCHAR(64) PRIMARY KEY, organization_name TEXT, city VARCHAR(150),
 state VARCHAR(100), postal_code VARCHAR(20), revenue NUMERIC(18,2), utilization BIGINT
);
CREATE TABLE IF NOT EXISTS warehouse.dim_provider (
 provider_id VARCHAR(64) PRIMARY KEY, organization_id VARCHAR(64), provider_name TEXT,
 gender VARCHAR(20), specialty TEXT, city VARCHAR(150), state VARCHAR(100),
 postal_code VARCHAR(20), utilization BIGINT,
 CONSTRAINT fk_dim_provider_organization FOREIGN KEY (organization_id)
 REFERENCES warehouse.dim_organization (organization_id)
);
CREATE TABLE IF NOT EXISTS warehouse.dim_payer (
 payer_id VARCHAR(64) PRIMARY KEY, payer_name TEXT, state_headquartered VARCHAR(100),
 amount_covered NUMERIC(18,2), amount_uncovered NUMERIC(18,2), revenue NUMERIC(18,2),
 covered_encounters BIGINT, uncovered_encounters BIGINT
);
CREATE TABLE IF NOT EXISTS warehouse.dim_date (
 date_key DATE PRIMARY KEY, calendar_year SMALLINT NOT NULL, calendar_quarter SMALLINT NOT NULL,
 month_number SMALLINT NOT NULL, month_name VARCHAR(12) NOT NULL,
 day_of_month SMALLINT NOT NULL, day_of_week SMALLINT NOT NULL
);

-- Grain: one row per source encounter (encounters.csv Id).
CREATE TABLE IF NOT EXISTS warehouse.fact_encounter (
 encounter_id VARCHAR(64) PRIMARY KEY, encounter_date DATE,
 patient_id VARCHAR(64) NOT NULL, organization_id VARCHAR(64),
 provider_id VARCHAR(64), payer_id VARCHAR(64), encounter_class VARCHAR(100),
 encounter_code VARCHAR(64), encounter_description TEXT,
 base_encounter_cost NUMERIC(18,2), total_claim_cost NUMERIC(18,2),
 payer_coverage NUMERIC(18,2), reason_code VARCHAR(64), reason_description TEXT,
 encounter_count SMALLINT NOT NULL DEFAULT 1,
 CONSTRAINT fk_fact_encounter_patient FOREIGN KEY (patient_id)
 REFERENCES warehouse.dim_patient (patient_id),
 CONSTRAINT fk_fact_encounter_organization FOREIGN KEY (organization_id)
 REFERENCES warehouse.dim_organization (organization_id),
 CONSTRAINT fk_fact_encounter_provider FOREIGN KEY (provider_id)
 REFERENCES warehouse.dim_provider (provider_id),
 CONSTRAINT fk_fact_encounter_payer FOREIGN KEY (payer_id)
 REFERENCES warehouse.dim_payer (payer_id),
 CONSTRAINT fk_fact_encounter_date FOREIGN KEY (encounter_date)
 REFERENCES warehouse.dim_date (date_key)
);

-- Grain: one row per source observation/lab result.
CREATE TABLE IF NOT EXISTS warehouse.fact_observation (
 observation_key BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 observation_date DATE, patient_id VARCHAR(64) NOT NULL, encounter_id VARCHAR(64),
 observation_code VARCHAR(64), description TEXT, value_text TEXT,
 value_numeric NUMERIC(20,6), units VARCHAR(100), observation_type VARCHAR(100),
 CONSTRAINT fk_fact_observation_patient FOREIGN KEY (patient_id)
 REFERENCES warehouse.dim_patient (patient_id),
 CONSTRAINT fk_fact_observation_encounter FOREIGN KEY (encounter_id)
 REFERENCES warehouse.fact_encounter (encounter_id),
 CONSTRAINT fk_fact_observation_date FOREIGN KEY (observation_date)
 REFERENCES warehouse.dim_date (date_key)
);

CREATE INDEX IF NOT EXISTS ix_fact_encounter_patient ON warehouse.fact_encounter (patient_id);
CREATE INDEX IF NOT EXISTS ix_fact_encounter_date ON warehouse.fact_encounter (encounter_date);
CREATE INDEX IF NOT EXISTS ix_fact_encounter_payer ON warehouse.fact_encounter (payer_id);
CREATE INDEX IF NOT EXISTS ix_fact_observation_patient ON warehouse.fact_observation (patient_id);
CREATE INDEX IF NOT EXISTS ix_fact_observation_date ON warehouse.fact_observation (observation_date);

-- Optional date-dimension seed from staging, if that table already exists.
-- Confirm your staging column names before running this block.
DO $$
BEGIN
 IF to_regclass('staging.encounters') IS NOT NULL THEN
  INSERT INTO warehouse.dim_date
   (date_key, calendar_year, calendar_quarter, month_number, month_name, day_of_month, day_of_week)
  SELECT DISTINCT start::date, EXTRACT(YEAR FROM start)::smallint,
   EXTRACT(QUARTER FROM start)::smallint, EXTRACT(MONTH FROM start)::smallint,
   TO_CHAR(start::date, 'FMMonth'), EXTRACT(DAY FROM start)::smallint,
   EXTRACT(ISODOW FROM start)::smallint
  FROM staging.encounters WHERE start IS NOT NULL
  ON CONFLICT (date_key) DO NOTHING;
 END IF;
 IF to_regclass('staging.observations') IS NOT NULL THEN
  INSERT INTO warehouse.dim_date
   (date_key, calendar_year, calendar_quarter, month_number, month_name, day_of_month, day_of_week)
  SELECT DISTINCT date::date, EXTRACT(YEAR FROM date)::smallint,
   EXTRACT(QUARTER FROM date)::smallint, EXTRACT(MONTH FROM date)::smallint,
   TO_CHAR(date::date, 'FMMonth'), EXTRACT(DAY FROM date)::smallint,
   EXTRACT(ISODOW FROM date)::smallint
  FROM staging.observations WHERE date IS NOT NULL
  ON CONFLICT (date_key) DO NOTHING;
 END IF;
END $;
